server:
  port: 8080
  servlet:
    context-path: /app
spring:
  jpa:
    database: postgresql
  application:
    name: AppApplication 
  datasource:
    url: jdbc:postgresql://localhost:5432/template?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: sistemas
    password: sistemas
    driver-class-name: org.postgresql.Driver
